stages:
  # - build
  # - test
  - dockerbuild
  - gkedeploy

# build: 
#   stage: build
#   script:
#     - cd ./'Product microservice'
#     - echo "Installing dependancies"
#     - npm install
#     - echo "Installation complete"
#     - npm run build
#     - echo "build successful"
#   artifacts:
#     paths:
#       - ./Product microservice/node_modules

# test:
#   stage: test
#   script:
#     - echo "Test placeholder "

docker build:
  stage: dockerbuild
  image: docker:stable
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - cd ./'Product microservice'
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_KEY
  script:
    - docker build . -t ikoitchev/product-service-k8s
    - docker push ikoitchev/product-service-k8s

gcloud deploy:
  stage: gkedeploy
  image: google/cloud-sdk
  script: 
    - cat $SERVICE_ACCOUNT > cred.json
    - echo cred.json
    - gcloud auth activate-service-account --key-file=cred.json
    - gcloud container clusters get-credentials ecom-cluster --region europe-west4 --project burnished-ember-369914
    - kubectl get namespaces
    - kubectl create -f 'Product microservice'/k8s/deployment.yaml


    



