stages:
  - build
  # - test
  - deploy

build: 
  image: node:latest
  stage: build
  script:
    - cd ./'Product microservice'
    - echo "Installing dependancies"
    - npm install
    - echo "Installation complete"
    - npm run build
    - echo "build successful"
  artifacts:
    paths:
      - ./Product microservice/node_modules

# test:
#   stage: test
#   script:
#     - echo "Test placeholder "
deploy:
  stage: deploy
  # image: google/cloud-sdk:alpine
  script:
    - cd ./'Product microservice'
    - docker login -u ikoitchev -p dckr_pat_U6BHri9aLrhmLToNqVn7oMvKY3Q
    - echo "logged in"
    - docker build . -t ikoitchev/product-service-k8s
    - echo "built"
    - docker push ikoitchev/product-service-k8s
    - echo "pushed"
    - glcoud --help
