stages:
  # - build
  # - test
  - dockerbuild
  - gkedeploy

# build: 
#   stage: build
#   script:
#     - cd ./'Product microservice'
#     - echo "Installing dependancies"
#     - npm install
#     - echo "Installation complete"
#     - npm run build
#     - echo "build successful"
#   artifacts:
#     paths:
#       - ./Product microservice/node_modules

# test:
#   stage: test
#   script:
#     - echo "Test placeholder "

docker build:
  stage: dockerbuild
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - cd ./'Product microservice'
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_KEY
  script:
    - docker build . -t ikoitchev/product-service-k8s
    - docker push ikoitchev/product-service-k8s

gcloud deploy:
  stage: gkedeploy
  image: google/cloud-sdk:latest
  script: 
    - docker container ls
    - docker run --name gcloud-config google/cloud-sdk gcloud auth activate-service-account --key-file=$SERVICE_ACCOUNT


