stages:
  # - build
  # - test
  - dockerbuild
  - gkedeploy

# build: 
#   stage: build
#   script:
#     - cd ./'Product microservice'
#     - echo "Installing dependancies"
#     - npm install
#     - echo "Installation complete"
#     - npm run build
#     - echo "build successful"
#   artifacts:
#     paths:
#       - ./Product microservice/node_modules

# test:
#   stage: test
#   script:
#     - echo "Test placeholder "

docker build:
  stage: dockerbuild
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - cd ./'Product microservice'
    - docker login -u ikoitchev -p dckr_pat_U6BHri9aLrhmLToNqVn7oMvKY3Q
  script:
    - docker build . -t ikoitchev/product-service-k8s
    - docker push ikoitchev/product-service-k8s


