image: node:latest

stages:
  - build
  # - test
  - deploy

build: 
  stage: build
  script:
    - cd ./'Product microservice'
    - echo "Installing dependancies"
    - npm install
    - echo "Installation complete"
    - npm run build
    - echo "build successful"
  artifacts:
    paths:
      - ./Product microservice/node_modules

# test:
#   stage: test
#   script:
#     - echo "Test placeholder "
deploy:
  stage: deploy
  script:
    - cd ./'Product microservice'
    - pwd
    - docker build . -t ikoitchev/product-service-k8s
    - docker login -u ikoitchev -p dckr_pat_U6BHri9aLrhmLToNqVn7oMvKY3Q
    - docker push ikoitchev/product-service-k8s
    - (New-Object Net.WebClient).DownloadFile("https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe", "$env:Temp\GoogleCloudSDKInstaller.exe") & $env:Temp\GoogleCloudSDKInstaller.exe
