http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: ['/images*', '/products']
serviceEndpoints:
  products:
    # url: 'product-service://ps:3008' # from inside the docker-compose
    url: 'http://localhost:3008' # when ran from vs code
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: products
              changeOrigin: true
