apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-k8s
spec:
  selector:
    matchLabels:
      app: product-service-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service-k8s
    spec:
      containers:
        - name: product-service-k8s
          image: ikoitchev/product-service-k8s
          env:
            - name: MONGODB_CONNECTION_PRODUCT
              valueFrom:
                secretKeyRef:
                  name: secret-ecom
                  key: mongoDB
                  optional: false
            - name: AMQP_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secret-ecom
                  key: amqp
                  optional: false
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secret-ecom
                  key: auth0-domain
                  optional: false
            - name: AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secret-ecom
                  key: auth0-audience
                  optional: false
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  name: secret-ecom
                  key: pepper
                  optional: false
          ports:
            - containerPort: 3008
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-k8s
spec:
  selector:
    app: product-service-k8s
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
  type: NodePort
