apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-k8s
spec:
  selector:
    matchLabels:
      app: gateway-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-k8s
    spec:
      containers:
        - name: gateway-k8s
          image: ikoitchev/gateway-k8s
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-k8s
spec:
  selector:
    app: gateway-k8s
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
