apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service-k8s
spec:
  selector:
    matchLabels:
      app: image-service-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: image-service-k8s
    spec:
      containers:
        - name: image-service-k8s
          image: ikoitchev/image-service-k8s
          ports:
            - containerPort: 3010
---
apiVersion: v1
kind: Service
metadata:
  name: image-service-k8s
spec:
  selector:
    app: image-service-k8s
  ports:
    - protocol: TCP
      port: 3010
  type: NodePort
